default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notification_service_development

test:
  <<: *default
  database: notification_service_test
  host: localhost
  # ENV POSTGRES_USER and POSTGRES_PASSWORD set in CI, usually empty
  # in local tests, where pg is usually running with no authentication required
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: notification_service_production
  username: notification_service
  password: <%= ENV["POSTGRES_PASSWORD"] %>
